using System.Collections.Generic;
using UnityEngine;

namespace VoidClash
{
    /// <summary>Root asset (lives in Resources) referencing every data asset the game needs.</summary>
    [CreateAssetMenu(menuName = "VoidClash/Game Database")]
    public class GameDatabase : ScriptableObject
    {
        public List<UnitData> units = new List<UnitData>();
        public List<BuildingData> buildings = new List<BuildingData>();

        [Header("Baked assets (optional, generated by setup)")]
        public List<string> materialNames = new List<string>();
        public List<Material> materials = new List<Material>();
        public List<string> clipNames = new List<string>();
        public List<AudioClip> clips = new List<AudioClip>();
        public List<string> visualPrefabNames = new List<string>();
        public List<GameObject> visualPrefabs = new List<GameObject>();

        public UnitData Unit(string id)
        {
            for (int i = 0; i < units.Count; i++) if (units[i].id == id) return units[i];
            Debug.LogError($"VoidClash: unknown unit id '{id}'");
            return null;
        }

        public BuildingData Building(string id)
        {
            for (int i = 0; i < buildings.Count; i++) if (buildings[i].id == id) return buildings[i];
            Debug.LogError($"VoidClash: unknown building id '{id}'");
            return null;
        }

        public Material FindMaterial(string name)
        {
            for (int i = 0; i < materialNames.Count && i < materials.Count; i++)
                if (materialNames[i] == name) return materials[i];
            return null;
        }

        public GameObject FindVisualPrefab(string key)
        {
            for (int i = 0; i < visualPrefabNames.Count && i < visualPrefabs.Count; i++)
                if (visualPrefabNames[i] == key) return visualPrefabs[i];
            return null;
        }

        public AudioClip FindClip(string name)
        {
            for (int i = 0; i < clipNames.Count && i < clips.Count; i++)
                if (clipNames[i] == name) return clips[i];
            return null;
        }

        public static GameDatabase BuildTransient()
        {
            var db = CreateInstance<GameDatabase>();
            db.units.AddRange(DataDefs.CreateUnits());
            db.buildings.AddRange(DataDefs.CreateBuildings());
            return db;
        }
    }
}
